### ISSUE TITLE
get into the TechEmPower Benchmarks.

### ISSUE THREAD

**Issue by windbender** [networknt/light-java-example#3]
https://www.techempower.com/benchmarks/

It's fun to run your own benchmark,  but this is pretty much the standard now since it actually cover some semi-real world use cases.

**Comment by stevehu** [comment]
I am aware of the benchmarks from techempower and here are the reasons that I have my own benchmark.

* As I understand, it stops publishing new round of benchmarks.
* Techempower only compares throughput and ignore other criteria, like response time. Some of the frameworks like GO fastHttp has good throughput but very high latency.
* This is to aim microservices other than generic web framework.
* The test is to gauge the raw throughput and latency other than real world user cases. 

Thanks.

**Comment by stevehu** [comment]
Are you able to turn off the log from dropwizard? I guess it will between 40K - 50K. In Light-Java, we are using a customized version of dropwizard metrics to hook up with Influxdb/Grafana.

**Comment by windbender** [comment]
Hi Steve:

- Round 13 was literally published yesterday, and they're trying to move to a sort of continuous basis.
- They do list latency including StdDev and Max thereof.
- There are is an entire "class" for "micro services" indicated by "Mcr"
- There is a test case called "Plaintext"   described as 'In this test, the framework responds with the simplest of responses: a "Hello, World" message rendered as plain text.'  I guess it's missing the exclamation mark,  so probably shouldn't be used :-)

So it does hit all your bullet points there.

**Comment by stevehu** [comment]
Thanks a lot for pointing me out the round 13 test. I will submit a pull request over there.
