### ISSUE TITLE
Integration with spring-boot?

### ISSUE THREAD

**Issue by hydra1983** [networknt/light-java-example#9]
Any plan to support the integration with spring-boot?

**Comment by stevehu** [comment]
Spring Boot is one of the most popular frameworks to build microservices and the services built on both platforms can talk to each other. Some of the components like mask, config etc. in light-java can be used by Spring Boot application but majority of the modules are middleware components that cannot be used in Sprint Boot. In my opinion, Spring Boot is too heavy to build microservices as it is slow and use a lot of memory.

I have done a real banking transaction service in Light-Java in comparison with Sprint-Boot(Undertow embedded) implemented by one of the world leading consulting firms for one of my clients and here is the result. (Sorry, the code cannot be open sourced)

Spring-Boot Throughput: 212.97 req/sec Latency: 66.07ms Memory: 1.5GB
Light-Java Throughput: 2319.34 req/sec Latency: 11.39ms Memory: 300MB

When you are deploying hundreds or thousands services within your organization, the infrastructure cost difference is huge. You need 10 time more medium t-shirt VMs to have the same throughtput with 1 Light-Java instance on small t-shirt VM. And to bring the response time to the same level, you will need a lot more Spring-Boot instances.

**Comment by hydra1983** [comment]
Got it. I'm going to remove spring boot from my micro service arch as well. As it consumes too much mem as you mentioned. Thanks for your sharing of the result.

**Comment by smaldini** [comment]
The spring boot reactive story is not released, what are you testing exactly, also please avoid benchmarking the 4 years old 1.1.0.M3 reactor we have now much more recent versions aligned with Spring 5 and Spring Boot 2 see the projectreactor.io code for only reactor https://github.com/reactor/projectreactor.io/blob/master/src/main/java/io/projectreactor/Application.java and https://github.com/bclozel/spring-reactive-university/tree/master/src/main/java/com/example for a spring boot app.

**Comment by stevehu** [comment]
@smaldini Spring-Boot Reactor actually performs very good even with a very old reactor. I am wondering if you could help to upgrade to the latest version. I am very curious how it performs. Thanks for the info.
